-- Esquema inicial del gestor de tareas (PostgreSQL)

CREATE TABLE usuario (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(50)  NOT NULL UNIQUE,
    nombre         VARCHAR(100) NOT NULL,
    contrasena     VARCHAR(100) NOT NULL,
    activo         BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE tarea (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo         VARCHAR(120)  NOT NULL,
    descripcion    VARCHAR(2000),
    estado         VARCHAR(20)   NOT NULL DEFAULT 'PENDIENTE',
    prioridad      VARCHAR(20)   NOT NULL DEFAULT 'MEDIA',
    fecha_limite   DATE,
    propietario_id BIGINT        NOT NULL REFERENCES usuario (id),
    creada_en      TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizada_en TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_tarea_estado    CHECK (estado IN ('PENDIENTE', 'EN_CURSO', 'HECHA')),
    CONSTRAINT ck_tarea_prioridad CHECK (prioridad IN ('BAJA', 'MEDIA', 'ALTA'))
);

CREATE INDEX ix_tarea_propietario ON tarea (propietario_id);

CREATE TABLE adjunto (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tarea_id       BIGINT       NOT NULL REFERENCES tarea (id) ON DELETE CASCADE,
    nombre         VARCHAR(255) NOT NULL,
    tipo_contenido VARCHAR(100),
    tamano         BIGINT       NOT NULL,
    clave          VARCHAR(64)  NOT NULL UNIQUE,
    subido_en      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_adjunto_tarea ON adjunto (tarea_id);
